---
title: "Rarefaction"
author: "Zach Kileeg"
date: "2024-10-16"
output: html_document
---
###load necessary libraries
```{r}
library(ggplot2)
library(stringr)
library(tidyr)
library(dplyr)
```

```{r}

#get input dataset from orthofinder where presence in an OG is represented by 1 and absence by 0


OG_Data=as.data.frame(read.csv("D:/Analysis_Output/Orthogroup_Assignment/Sep2024/Kinases/Orthofinder_out/Results_Dec9/RLKs_Only/RLKs_HOGs_BlastSplit.csv"))
colnames(OG_Data)[1] = "HOG"

families = unique(OG_Data$Family)
#OG_Data = OG_Data %>% filter(Family == "MLRR")

#randomize order

species_number = 146
num_iterations = 1000

#holding_list = vector("list", length=num_iterations)


core_genome_matrix = matrix(nrow=num_iterations,ncol=species_number)
rlkome_genome_matrix = matrix(nrow=num_iterations, ncol=species_number)
#rownames(holding_matrix) = c("RLKome_size", "Core_genome_size")

#this for loop is for the number of iterations wanted to the rarefaction. The more numbers, the smoother the average curve. 1000 is default cuz why not. 
for (j in 1:num_iterations){
  
print(c("Iteration", j), quote=FALSE)
  
#get a random subsamble starting at the fourth column (first data column) until the last and do it for 146 samples (ecotype number)
OGs_randomized = cbind(OG_Data[,1:3],sample(OG_Data[,4:ncol(OG_Data)],species_number, replace=FALSE))


#set holding variable to hold new OGs
OGs_collected = vector()

#start with vector of all HOGs. We will use this and intersect to get core as we go along
core_ogs = OG_Data$HOG

#loop over columns (num species/ecotypes/observations)
for (i in 1:(ncol(OGs_randomized)-3)){
  
  #filter by those with presence of a gene in the OG
  filtered_OGs = OGs_randomized %>% filter (OGs_randomized[,i+3] == 1)
  
  #find intersection of the HOGs we have and the new ones added. If they intersect, that's the 'core genome' 
  core_ogs = intersect(core_ogs, filtered_OGs$HOG)
  
  
  #OG_list = filtered_OGs$HOG
  # find difference between the new OGs and the one's we've already found to see if there are new ones 
  new_ogs = setdiff(filtered_OGs$HOG,OGs_collected)
  
  
  
  
  #add new ogs to growing collection
  OGs_collected = c(OGs_collected,new_ogs)
  
  #add the NOG count to matrix with rows = iterations, i = genome
  rlkome_genome_matrix[j, i] = length(OGs_collected)
  core_genome_matrix[j,i] = length(core_ogs)
  
}


  
}


new_genes_per_iteration = matrix(nrow=nrow(rlkome_genome_matrix), ncol=ncol(rlkome_genome_matrix))
new_genes_per_iteration[,1] = rlkome_genome_matrix[,1]

for (newgene in 2:ncol(new_genes_per_iteration)){
  
  new_genes_per_iteration[,newgene] = rlkome_genome_matrix[,newgene] - rlkome_genome_matrix[,(newgene-1)]
  
}

```

#plot rarefaction and collectors curves
```{r}

rlkome_genome_df = as.data.frame(rlkome_genome_matrix)
rlkome_genome_df = as.data.frame(sapply(rlkome_genome_df, as.numeric))
rlkome_genome_df = cbind(rownames(rlkome_genome_df), rlkome_genome_df)
colnames(rlkome_genome_df) = c("Iteration", 1:(ncol(rlkome_genome_df)-1))

average_rlkome_df = as.data.frame(sapply(rlkome_genome_df[,2:ncol(rlkome_genome_df)], mean))
average_rlkome_df = cbind(c(1:species_number), average_rlkome_df)
colnames(average_rlkome_df) = c("genome", "OGs")
#rownames(rlkome_genome_matrix) = c(1:num_iterations)



#rlkome_genome_df = rlkome_genome_df[,1:20]




core_genome_df= as.data.frame(core_genome_matrix)
core_genome_df = as.data.frame(sapply(core_genome_df, as.numeric))
core_genome_df = cbind(1:num_iterations,core_genome_df)
colnames(core_genome_df) = c("Iteration", 1:(ncol(core_genome_df)-1))

average_coregenome_df = as.data.frame(sapply(core_genome_df[,2:ncol(core_genome_df)], mean))
average_coregenome_df = cbind(c(1:species_number),average_coregenome_df)
colnames(average_coregenome_df) = c("genome", "OGs")

plotting_coregenome = gather(core_genome_df, genome, value, -"Iteration")
plotting_rlkome = gather(rlkome_genome_df, genome, value, -"Iteration")
#plotting_rlkome = plotting_rlkome[order(plotting_rlkome$Iteration),]





plotting_rlkome %>% 
  ggplot(aes(x=as.numeric(genome), y=as.numeric(value), group=Iteration)) + geom_line(color="grey") + geom_line(data=average_rlkome_df, aes(x=as.numeric(genome), y=as.numeric(OGs), color="PanRLKome"),inherit.aes=FALSE) +
  geom_line(data=plotting_coregenome, aes(x=as.numeric(genome), y=as.numeric(value), group=Iteration), color="grey", inherit.aes=FALSE)   + geom_line(data=average_coregenome_df, aes(x=as.numeric(genome), y=as.numeric(OGs), color="Core_Genome"), inherit.aes=FALSE) + 
  scale_color_manual(name = "", breaks = c("PanRLKome", "Core_Genome"), labels=c("PanRLKome", "Core_Genome"), values=c("PanRLKome" = "red", "Core_Genome" = "darkblue" )) +
  theme_bw() + xlab("Genomes") + ylab("OGs Discovered")

#ggsave("D:/Analysis_Output/Orthogroup_Assignment/Sep2024/Kinases/Orthofinder_out/Results_Dec9/Figures/Rarefaction_HOGs_notsplit_notsingle.png", height=6, width=6, dpi=600)

ggsave("D:/Analysis_Output/Orthogroup_Assignment/Sep2024/Kinases/Orthofinder_out/Results_Dec9/Figures/Rarefaction_HOGs_blastsplit.png", height=6, width=6, dpi=600)



```

###plot average number of genes found
```{r}

new_genes_per_iteration_df = as.data.frame(new_genes_per_iteration)
new_genes_per_iteration_df = as.data.frame(sapply(new_genes_per_iteration_df, as.numeric))
new_genes_per_iteration_df = cbind(rownames(new_genes_per_iteration_df), new_genes_per_iteration_df)
colnames(new_genes_per_iteration_df) = c("Iteration", 1:(ncol(new_genes_per_iteration_df)-1))

average_newgene_df = as.data.frame(sapply(new_genes_per_iteration_df[,2:ncol(new_genes_per_iteration_df)], mean))
average_newgene_df = cbind(c(1:species_number), average_newgene_df)
colnames(average_newgene_df) = c("genome", "OGs")
#rownames(rlkome_genome_matrix) = c(1:num_iterations)

plotting_newgenes = gather(new_genes_per_iteration_df, genome, value, -"Iteration")
plotting_newgenes = plotting_newgenes[1001:nrow(plotting_newgenes), ]

average_newgene_df = average_newgene_df %>% filter(OGs <100)


plotting_newgenes %>% 
  ggplot(aes(x=as.numeric(genome), y=as.numeric(value), group=Iteration)) + geom_line(color="grey") + geom_line(data=average_newgene_df, aes(x=as.numeric(genome), y=as.numeric(OGs), color="Average new OGs"),inherit.aes=FALSE) + scale_color_manual(values="darkgreen") + theme_bw() + xlab("Genomes") + ylab("New OGs")
#+
 # geom_line(data=plotting_coregenome, aes(x=as.numeric(genome), y=as.numeric(value), group=Iteration), color="grey", inherit.aes=FALSE)   + geom_line(data=average_coregenome_df, aes(x=as.numeric(genome), y=as.numeric(OGs), color="Core_Genome"), inherit.aes=FALSE) + 
#  scale_color_manual(name = "", breaks = c("PanRLKome", "Core_Genome"), labels=c("PanRLKome", "Core_Genome"), values=c("PanRLKome" = "red", "Core_Genome" = "darkblue" )) +
 # theme_bw() + xlab("Genomes") + ylab("OGs Discovered")

#ggsave("D:/Analysis_Output/Orthogroup_Assignment/Sep2024/Kinases/Orthofinder_out/Results_Dec9/Figures/Rarefaction_HOGs_notsplit_notsingle.png", height=6, width=6, dpi=600)

ggsave("D:/Analysis_Output/Orthogroup_Assignment/Sep2024/Kinases/Orthofinder_out/Results_Dec9/Figures/Newgenesfound_HOGs_PrivateIncluded.png", height=2, width=6, dpi=600)


```

##this chunk takes as input a csv file containing gene family and HOG counts. Counts private included
```{r}

#library(tidyverse)
library(dplyr)

#get input dataset from orthofinder. This will be the actual values of counts per OG split into hierarchical OGs

#OG_Data=as.data.frame(read.csv("D:/Analysis_Output/Orthogroup_Assignment/Sep2024/Kinases/Orthofinder_out/Nov2024_NOGs_include_private.csv"))
#OG_Data=as.data.frame(read.csv("D:/Analysis_Output/Orthogroup_Assignment/Sep2024/Kinases/Orthofinder_out/Results_Dec9/RLKs_Only/RLKs_HOGs_BlastSplit.csv"))
OG_Data= as.data.frame(read.csv("D:/Analysis_Output/Orthogroup_Assignment/Sep2024/Kinases/Orthofinder_out/Results_Dec9/RLKs_Only/RLKs_HOGs_Counts.csv"))
colnames(OG_Data)[1] = "HOG"

families = unique(OG_Data$Family)
#OG_Data = OG_Data %>% filter(Family == "MLRR")

#prepare new potential OGs

df_to_return = data.frame()
removal_OGs = vector()

#Loop over every row in the OG Gene count data
for (l in 1:nrow(OG_Data)){
  
  #First, we have to split the OGs to ensure each OG ONLY has 1 gene from each ecotype.
  if (max(OG_Data[l,4:ncol(OG_Data)]) > 1){
    
    removal_OGs = c(removal_OGs, OG_Data[l,1])
  
  separation_num= max(OG_Data[l,4:ncol(OG_Data)]) - 1
  
 separation_df = rbind(OG_Data[l,], OG_Data[rep(l,separation_num),])
  
  #separation_matrix = as.data.frame(rep(OG_Data[l,], times=separation_num))
  #separation_matrix = matrix( nrow = separation_num, ncol=ncol(OG_Data))
  #colnames(separation_matrix) = colnames(OG_Data)
  
  
  
  
  
  #Remove duplicate names 
  for (k in 1:nrow(separation_df)){
    
    separation_df[k,4:ncol(separation_df)] = separation_df[k,4:ncol(separation_df)] - (k-1)
    
    separation_df[k,1] = paste(separation_df[k,1], "_", k, sep="")
    
  }
 
  

  # if the value is above 0, change it to 1. If it's below 0, change it to 0
  separation_df[,4:ncol(separation_df)] = ifelse(separation_df[,4:ncol(separation_df)] >0, 1, 0)
  
  df_to_return = rbind(df_to_return, separation_df[1:nrow(separation_df),])
  #df_to_return = filter(df_to_return, )
  
  }
  
}

#Update the OG data to be in the separated format. Now we can start counting 
OG_Data = OG_Data %>% filter(!(HOG %in% removal_OGs))
OG_Data = rbind(OG_Data, df_to_return)


#OG_Data = OG_Data[sum(OG_Data[,4:ncol(OG_Data)]) >=1 ,]
#OG_Data = OG_Data[sum(sapply(OG_Data[,4:ncol(OG_Data)], as.numeric)) >=2 ,]
#OG_Data = OG_Data[rowSums(OG_Data[,4:ncol(OG_Data)]) >=2,]
OG_Data = OG_Data[rowSums(OG_Data[,4:ncol(OG_Data)]) >=1,]    #get total number of genes in each OG 

#set the number of input species/ecotypes and the number of iterations
species_number = 146
num_iterations = 1000

#holding_list = vector("list", length=num_iterations)

#initialize the output matrices
core_genome_matrix = matrix(nrow=num_iterations,ncol=species_number)
rlkome_genome_matrix = matrix(nrow=num_iterations, ncol=species_number)
#rownames(holding_matrix) = c("RLKome_size", "Core_genome_size")

#this for loop is for the number of iterations wanted to the rarefaction. The more numbers, the smoother the average curve. 1000 is default bceause it gives a nice, smooth curve. More the better obviously. 
for (j in 1:num_iterations){
  
print(c("Iteration", j), quote=FALSE)
  
#get a random subsamble starting at the fourth column (first data column) until the last and do it for 146 samples (ecotype number)
OGs_randomized = cbind(OG_Data[,1:3],sample(OG_Data[,4:ncol(OG_Data)],species_number, replace=FALSE))


#set holding variable to hold new OGs
OGs_collected = vector()

#start with vector of all HOGs. We will use this and intersect to get core as we go along
core_ogs = OG_Data$HOG

#loop over columns (num species/ecotypes/observations)
for (i in 1:(ncol(OGs_randomized)-3)){
  
  #filter by those with presence of a gene in the OG
  filtered_OGs = OGs_randomized %>% filter (OGs_randomized[,i+3] == 1)
  
  #find intersection of the HOGs we have and the new ones added. If they intersect, that's the 'core genome' 
  core_ogs = intersect(core_ogs, filtered_OGs$HOG)
  
  
  #OG_list = filtered_OGs$HOG
  # find difference between the new OGs and the one's we've already found to see if there are new ones 
  new_ogs = setdiff(filtered_OGs$HOG,OGs_collected)
  
  
  
  
  #add new ogs to growing collection
  OGs_collected = c(OGs_collected,new_ogs)
  
  #add the NOG count to matrix with rows = iterations, i = genome
  rlkome_genome_matrix[j, i] = length(OGs_collected)
  core_genome_matrix[j,i] = length(core_ogs)
  
  
}


  
}

#Now figure out the number of new genes found per iteration and add it to the output matrix 
new_genes_per_iteration = matrix(nrow=nrow(rlkome_genome_matrix), ncol=ncol(rlkome_genome_matrix))
new_genes_per_iteration[,1] = rlkome_genome_matrix[,1]

for (newgene in 2:ncol(new_genes_per_iteration)){
  
  new_genes_per_iteration[,newgene] = rlkome_genome_matrix[,newgene] - rlkome_genome_matrix[,(newgene-1)]
  
}

```

#plot rarefaction and collectors curves Private genes included
```{r}

rlkome_genome_df = as.data.frame(rlkome_genome_matrix)
rlkome_genome_df = as.data.frame(sapply(rlkome_genome_df, as.numeric))
rlkome_genome_df = cbind(rownames(rlkome_genome_df), rlkome_genome_df)
colnames(rlkome_genome_df) = c("Iteration", 1:(ncol(rlkome_genome_df)-1))


average_rlkome_df = as.data.frame(sapply(rlkome_genome_df[,2:ncol(rlkome_genome_df)], mean))
average_rlkome_df = cbind(c(1:species_number), average_rlkome_df)
colnames(average_rlkome_df) = c("genome", "OGs")
#rownames(rlkome_genome_matrix) = c(1:num_iterations)



#rlkome_genome_df = rlkome_genome_df[,1:20]




core_genome_df= as.data.frame(core_genome_matrix)
core_genome_df = as.data.frame(sapply(core_genome_df, as.numeric))
core_genome_df = cbind(1:num_iterations,core_genome_df)
colnames(core_genome_df) = c("Iteration", 1:(ncol(core_genome_df)-1))

average_coregenome_df = as.data.frame(sapply(core_genome_df[,2:ncol(core_genome_df)], mean))
average_coregenome_df = cbind(c(1:species_number),average_coregenome_df)
colnames(average_coregenome_df) = c("genome", "OGs")

plotting_coregenome = gather(core_genome_df, genome, value, -"Iteration")
plotting_rlkome = gather(rlkome_genome_df, genome, value, -"Iteration")
#plotting_rlkome = plotting_rlkome[order(plotting_rlkome$Iteration),]





plotting_rlkome %>% 
  ggplot(aes(x=as.numeric(genome), y=as.numeric(value), group=Iteration)) + geom_line(color="grey") + geom_line(data=average_rlkome_df, aes(x=as.numeric(genome), y=as.numeric(OGs), color="PanRLKome"),inherit.aes=FALSE) +
  geom_line(data=plotting_coregenome, aes(x=as.numeric(genome), y=as.numeric(value), group=Iteration), color="grey", inherit.aes=FALSE)   + geom_line(data=average_coregenome_df, aes(x=as.numeric(genome), y=as.numeric(OGs), color="RLK_Core"), inherit.aes=FALSE) + 
  scale_color_manual(name = "", breaks = c("PanRLKome", "RLK_Core"), labels=c("PanRLKome", "RLK_Core"), values=c("PanRLKome" = "red", "RLK_Core" = "darkblue" )) +
  theme_bw() + xlab("Genomes") + ylab("OGs Discovered")

ggsave("D:/Analysis_Output/Orthogroup_Assignment/Sep2024/Kinases/Orthofinder_out/Figures/Nov2024_Rarefaction_include_private.png", height=6, width=6, dpi=600)

#ggsave("D:/Analysis_Output/Orthogroup_Assignment/Sep2024/Kinases/Orthofinder_out/Results_Dec9/Figures/Rarefaction_HOGs_blastsplit.png", height=6, width=6, dpi=600)


```

